from setuptools import setup, find_packages

setup(
    name='gptsovits',
    packages=find_packages(),
    include_package_data=True,
    description='GPT SoVITS',
    version='0.0.1',
    url='https://github.com/eschmidbauer/gptsovits',
    author='Emmanuel Schmidbauer',
    author_email='eschmidbauer@gmail.com',
    keywords=['pip', 'gptsovits'],
    python_requires='>3.9',
    install_requires=[
        'numpy==1.23.4',
        'scipy',
        'tensorboard',
        'librosa==0.9.2',
        'numba==0.56.4',
        'pytorch-lightning',
        'ffmpeg-python',
        'onnxruntime',
        'tqdm',
        'funasr==1.0.27',
        'cn2an',
        'pypinyin',
        'pyopenjtalk>=0.3.4',
        'g2p_en',
        'torchaudio',
        'modelscope==1.10.0',
        'sentencepiece',
        'transformers',
        'chardet',
        'PyYAML',
        'psutil',
        'jieba_fast',
        'jieba',
        'LangSegment>=0.2.0',
        'wordsegment',
        'rotary_embedding_torch',
        'pyjyutping',
        'g2pk2',
        'opencc',
        'matplotlib'
    ]
)
