default_v2:
  bert_base_path: pretrained_models/chinese-roberta-wwm-ext-large
  cnhuhbert_base_path: pretrained_models/chinese-hubert-base
  device: cpu
  is_half: false
  t2s_weights_path: pretrained_models/gsv-v2final-pretrained/s1bert25hz-5kh-longer-epoch=12-step=369668.ckpt
  version: v2
  vits_config_path: configs/s2_config.json
  vits_weights_path: pretrained_models/gsv-v2final-pretrained/s2G2333k.pth
